set(BOARD_REVISIONS "ALL")
if(NOT DEFINED BOARD_REVISION)
  set(BOARD_REVISION "ALL")
else()
  if(NOT BOARD_REVISION IN_LIST BOARD_REVISIONS)
    message(FATAL_ERROR "${BOARD_REVISION} is not a valid revision for aipi_eyes_s2 Accepted revisions: ${BOARD_REVISIONS}")
  endif()
endif()
